# Generated by Django 5.2.4 on 2025-08-26 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0004_alter_product_brand_alter_product_category_and_more'),
        ('secondapp', '0008_alter_brand_name_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondapp_products', to='secondapp.brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondapp_products', to='secondapp.category'),
        ),
    ]
