# Generated by Django 5.2.4 on 2025-09-20 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0008_offer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
