# Generated by Django 5.2.8 on 2025-11-21 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0005_adminuser_delete_adminprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminuser',
            old_name='employee_id',
            new_name='employeeid',
        ),
        migrations.RenameField(
            model_name='adminuser',
            old_name='security_code',
            new_name='securitycode',
        ),
    ]
