# Generated by Django 5.2.8 on 2025-11-21 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0006_rename_employee_id_adminuser_employeeid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminuser',
            old_name='employeeid',
            new_name='employeeId',
        ),
        migrations.RenameField(
            model_name='adminuser',
            old_name='securitycode',
            new_name='securityCode',
        ),
    ]
