# Generated by Django 5.2.4 on 2025-07-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sampletable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=10)),
                ('weight', models.FloatField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('name', models.CharField(max_length=150)),
                ('feedback', models.TextField()),
                ('date_of_birth', models.DateField(auto_now=True)),
                ('date_of_birth_with_time', models.DateTimeField()),
                ('bith_time', models.TimeField()),
                ('is_admin', models.BooleanField()),
            ],
        ),
    ]
