# Generated by Django 5.2.4 on 2025-07-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='shoping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('age', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Sampletable',
        ),
    ]
