# Generated by Django 5.2.4 on 2025-07-19 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0005_alter_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
    ]
