# Generated by Django 5.2.8 on 2025-11-20 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_shopizen', '0012_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
    ]
